image: eclipse-temurin:21-jdk

variables:
  BAZELISK_VERSION: "latest"

before_script:
  - echo "JADEX_VERSION=$JADEX_VERSION"
  - apt-get update
  - apt-get install -y curl build-essential python3 sshpass git
  - python3 --version
  - curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o /usr/local/bin/bazel
  - chmod +x /usr/local/bin/bazel
  - bazel version
  - . ./env.sh

stages:
  - build
  - test
  - benchmark
  - deploy

build:
  stage: build
  script:
    - bazel build //...
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .bazel
      - ~/.cache/bazel

test:
  stage: test
  script:
    - bazel test $(bazel query '//... except //benchmark/...')

  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .bazel
      - ~/.cache/bazel

benchmark:
  stage: benchmark
  script:
    - bazel test //benchmark/... --test_output=errors
  allow_failure: true
  cache:
    - key: "$CI_COMMIT_REF_NAME"
      policy: pull
      paths:
        - .bazel
        - ~/.cache/bazel

    - key: benchmarks-$CI_COMMIT_REF_SLUG
      paths:
        - benchmark/*/.benchmark_bazel
      when: always
  #rules:
  #  - if: '$CI_COMMIT_REF_SLUG =~ /main/'
  tags:
    - benchmark

# purge_benchmarks:
#  stage: benchmark
#  script:
#    - bazel run //benchmark:purge
#  cache:
#    - key: "$CI_COMMIT_REF_NAME"
#      policy: pull
#      paths:
#        - .bazel
#        - ~/.cache/bazel
#
#    - key: benchmarks-$CI_COMMIT_REF_SLUG
#      paths:
#        - benchmark/*/.benchmark_bazel
#  when: manual
#  tags:
#    - benchmark

#deployCentral:
#  stage: deploy
#  script:
#    - bazel run //:publish
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: pull
#    paths:
#      - .bazel
#      - ~/.cache/bazel
#  rules:
#    - if: '$CI_COMMIT_REF_SLUG =~ /main/'

deployZip:
  stage: deploy
  script:
    - echo "PASSWORD_LENGTH=${#SSH_PASSWORD}"
    - bazel build //application/launcher:launcher_deploy.jar

    - BAZEL_BIN=$(bazel info bazel-bin)
    - JAR="$BAZEL_BIN/application/launcher/launcher_deploy.jar"
    - echo "JAR=$JAR"
    - ls -l "$JAR"

    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "rm -rf /www/releases/$JADEX_VERSION && mkdir -p /www/releases/$JADEX_VERSION"

    - sshpass -p "$SSH_PASSWORD" scp -P "$SSH_PORT" "$JAR" "$SSH_USER@$SSH_HOST:/www/releases/$JADEX_VERSION/"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .bazel
      - ~/.cache/bazel
  #rules:
  #  - if: '$JADEX_VERSION' #'$CI_COMMIT_BRANCH == "main" &&
  #rules:
  #  - if: '$CI_COMMIT_BRANCH == "main"'







