image: eclipse-temurin:21-jdk

variables:
  BAZELISK_VERSION: "latest"

before_script:
  - apt-get update
  - apt-get install -y curl build-essential python3
  - curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o /usr/local/bin/bazel
  - chmod +x /usr/local/bin/bazel
  - bazel version

stages:
  - build
  - test
  - benchmark
  - deploy

build:
  stage: build
  script:
    - bazel build //...
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .bazel
      - ~/.cache/bazel

test:
  stage: test
  script:
    - bazel test //...
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .bazel
      - ~/.cache/bazel

benchmark:
  stage: benchmark
  script:
    - bazel test //benchmark/... --test_output=errors
  allow_failure: true
  cache:
    - key: "$CI_COMMIT_REF_NAME"
      policy: pull
      paths:
        - .bazel
        - ~/.cache/bazel

    - key: benchmarks-$CI_COMMIT_REF_SLUG
      paths:
        - benchmark/*/.benchmark_bazel
      when: always
  rules:
    - if: '$CI_COMMIT_REF_SLUG =~ /main/'
  tags:
    - benchmark

# purge_benchmarks:
#  stage: benchmark
#  script:
#    - bazel run //benchmark:purge
#  cache:
#    - key: "$CI_COMMIT_REF_NAME"
#      policy: pull
#      paths:
#        - .bazel
#        - ~/.cache/bazel
#
#    - key: benchmarks-$CI_COMMIT_REF_SLUG
#      paths:
#        - benchmark/*/.benchmark_bazel
#  when: manual
#  tags:
#    - benchmark

# deployZip:
#  stage: deploy
#  script:
#    - bazel build //:deployZip
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: pull
#    paths:
#      - .bazel
#      - ~/.cache/bazel
#  rules:
#    - if: '$CI_COMMIT_REF_SLUG =~ /main/'

#deployCentral:
#  stage: deploy
#  script:
#    - bazel run //:publish
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: pull
#    paths:
#      - .bazel
#      - ~/.cache/bazel
#  rules:
#    - if: '$CI_COMMIT_REF_SLUG =~ /main/'







