# AUTO-GENERATED by env.sh — nicht manuell bearbeiten
# Erstellt: 2026-06-26T13:16:18Z

JADEX_VERSION = "5.0-beta4"

CENTRAL_USER = ""
CENTRAL_PASSWORD = ""
REPO_CENTRAL_URL = ""

REPOS = "central"
REPO_ID = ""

SSH_USER = ""
SSH_HOST = ""
SSH_PORT = ""
SSH_FINGERPRINT = ""
