# AUTO-GENERATED by env.sh — nicht manuell bearbeiten
# Erstellt: 2026-07-14T18:41:27Z

JADEX_VERSION = "5.0-beta5"

CENTRAL_USER = ""
CENTRAL_PASSWORD = ""
REPO_CENTRAL_URL = ""

REPOS = "central"
REPO_ID = ""

SSH_USER = ""
SSH_HOST = ""
SSH_PORT = ""
SSH_FINGERPRINT = ""
