#!/usr/bin/env python3
"""
generate_eclipse_projects.py

Generates Eclipse-compatible .project / .classpath files for every
java_library / java_test / java_binary Bazel package in a bzlmod
(MODULE.bazel-based, Bazel 9) workspace, so the resulting folders can be
opened directly in Eclipse *or* VS Code (via the "Language Support for
Java" extension, which has a built-in importer for Eclipse-style
projects) without either IDE needing to understand Bazel at all.

WHY THIS WORKS RELIABLY
------------------------
We deliberately do NOT hand-parse BUILD files or deps.bazel with regex.
Your deps.bazel computes DEPS via a Starlark helper (_maven_to_bazel),
which only Bazel itself can evaluate correctly. Instead we ask Bazel:

  1. `bazel query --output=xml` for every java_library/java_test/java_binary
     target -> gives us the fully-resolved srcs/resources/deps/runtime_deps
     lists (globs and macros already expanded).
  2. `bazel cquery --output=starlark` (a single batched call) to resolve
     every @maven//:... target to its real jar file path on disk.

One Eclipse project is generated per Bazel *package* (directory), merging
its java_library and java_test targets into one project (Eclipse doesn't
usually need main/test split as separate projects for this use case).

REGENERATION
------------
This is designed to be re-run any time BUILD files / deps.bazel / your
maven artifact list changes. It always overwrites its own output, so
regenerating is safe and expected -- see the AUTO-GENERATED header it
writes into every file.

USAGE
-----
    python3 generate_eclipse_projects.py [--workspace DIR] [--jdk 21]

Then in Eclipse:  File > Import > General > Existing Projects into
Workspace > select your repo root > it will find every generated project.

In VS Code: just open the repo root folder (or add each project folder
as a workspace folder); the Java extension auto-detects the Eclipse
project files.
"""

import argparse
import os
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict

# Bazel rule kinds we turn into Eclipse projects.
SUPPORTED_KINDS = {"java_library", "java_test", "java_binary"}

# Conventional source directories we look for on disk inside each
# package. Adjust here if your layout ever differs from
# src/main/java, src/main/resources, src/test/java, src/test/resources.
SRC_DIR_CANDIDATES = [
    "src/main/java",
    "src/main/resources",
    "src/generated/javacc",
    "src/generated/jjtree",
    "src/test/java",
    "src/test/resources",
    "src/testFixtures/java",
    "src/testFixtures/resources",
]
AUTO_GEN_NOTICE = (
    "AUTO GENERATED by generate_eclipse_projects.py, do not hand edit, "
    "just re-run the script after Bazel deps change."
)

GENERATED_DIRS = {
    ".git",
    ".jdt-output",
    ".eclipse-bin",
    "bin",
}

def run(cmd, cwd):
    """Run a subprocess, raise with full stderr on failure."""
    proc = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True
    )
    if proc.returncode != 0:
        sys.stderr.write(f"$ {' '.join(cmd)}\n")
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"Command failed: {' '.join(cmd)}")
    return proc.stdout

def clean_all_bin_dirs(workspace):
    """Remove all bin directories from the workspace before Bazel queries."""
    removed = []

    print(f"  Scanning for bin directories under {workspace} ...", flush=True)

    for dirpath, dirnames, filenames in os.walk(workspace, topdown=True):
        # Never descend into Bazel/VCS trees.
        dirnames[:] = [
            d for d in dirnames
            if d not in (".git", "bazel-out", "bazel-bin", "bazel-testlogs")
            and not d.startswith("bazel-")
        ]

        if "bin" not in dirnames:
            continue

        bin_dir = os.path.join(dirpath, "bin")
        print(f"  Removing {os.path.relpath(bin_dir, workspace)} ...", flush=True)

        try:
            shutil.rmtree(bin_dir)
            removed.append(bin_dir)
        except OSError as e:
            print(f"  WARNING: could not remove {bin_dir}: {e}", flush=True)

        # Do not descend into the directory we just removed.
        dirnames.remove("bin")

    return removed


def bazel_info(key, workspace):
    return run(["bazel", "info", key], cwd=workspace).strip()


def query_all_java_rules(workspace):
    """Single bazel query for every relevant java_* target in the repo."""
    kinds = "|".join(SUPPORTED_KINDS)
    expr = f'kind("^({kinds}) rule$", //...)'

    xml_text = run(
        ["bazel", "query", expr, "--output=xml", "--noimplicit_deps"],
        cwd=workspace,
    )

    root = ET.fromstring(xml_text)
    rules = []

    for rule in root.findall("rule"):
        data = {
            "kind": rule.get("class"),
            "name": rule.get("name"),
        }

        for list_name in ("srcs", "resources", "deps", "runtime_deps"):
            elem = rule.find(f"list[@name='{list_name}']")
            data[list_name] = (
                [lbl.get("value") for lbl in elem.findall("label")]
                if elem is not None
                else []
            )

        jc = rule.find("list[@name='javacopts']")
        data["javacopts"] = (
            [s.get("value") for s in jc.findall("string")]
            if jc is not None
            else []
        )

        rules.append(data)

    return rules


def label_package(label):
    """'//util/common:common' -> 'util/common'; '//:root' -> ''."""
    pkg = label.split(":")[0]
    return pkg[2:] if pkg.startswith("//") else pkg


def project_name_for_package(pkg_path):
    return pkg_path.replace("/", ".") if pkg_path else "root"


def guess_jdk_version(javacopts_lists, default_jdk):
    best = None
    for opts in javacopts_lists:
        for i, tok in enumerate(opts):
            if tok in ("-target", "--release", "-source") and i + 1 < len(opts):
                nxt = opts[i + 1]
                if nxt.isdigit():
                    best = max(best or 0, int(nxt))
    return best or default_jdk

def resolve_maven_jars(maven_labels, workspace):
    """
    Resolve @maven//:... labels to actual JAR files.

    Each Maven target is queried individually because batched cquery
    with set(...) does not reliably return the outputs with the current
    Bazel/rules_jvm_external setup.
    """
    if not maven_labels:
        return {}

    execroot = bazel_info("execution_root", workspace)
    jars = {}

    print(
        f"  Resolving {len(maven_labels)} Maven dependency target(s) ..."
    )

    for index, label in enumerate(sorted(maven_labels), 1):
        print(f"  [{index}/{len(maven_labels)}] {label}")

        proc = subprocess.run(
            [
                "bazel",
                "cquery",
                label,
                "--output=starlark",
                "--starlark:expr",
                "'%s\t%s' % (str(target.label), ','.join([f.path for f in target.files.to_list()]))",
            ],
            cwd=workspace,
            capture_output=True,
            text=True,
        )

        if proc.returncode != 0:
            sys.stderr.write(proc.stdout)
            sys.stderr.write(proc.stderr)
            print(f"    WARNING: cquery failed for {label}")
            continue

        for line in proc.stdout.splitlines():
            line = line.strip()

            if not line or "\t" not in line:
                continue

            resolved_label, paths = line.split("\t", 1)

            for rel_path in paths.split(","):
                rel_path = rel_path.strip()

                if not rel_path.endswith(".jar"):
                    continue

                abs_path = os.path.normpath(
                    os.path.join(execroot, rel_path)
                )

                if not os.path.isfile(abs_path):
                    continue

                src_path = None
                candidate = abs_path[:-4] + "-sources.jar"

                if os.path.isfile(candidate):
                    src_path = candidate

                jars[label] = {
                    "jar": abs_path,
                    "srcjar": src_path,
                }

                break

            if label in jars:
                break

    print(
        f"  Resolved {len(jars)}/{len(maven_labels)} "
        "Maven dependency target(s)."
    )

    for label in sorted(maven_labels):
        if label not in jars:
            print(f"  WARNING: could not resolve Maven JAR: {label}")

    return jars

def build_project_models(rules, workspace):
    """Build Eclipse project models from Bazel rules."""

    projects = defaultdict(
        lambda: {
            "internal_deps": set(),
            "maven_deps": set(),
            "other_deps": set(),
            "javacopts": [],
            "srcs": [],
        }
    )

    target_to_pkg = build_target_to_java_package(rules)

    # First collect sources and direct Maven deps.
    for rule in rules:
        pkg = label_package(rule["name"])
        model = projects[pkg]

        model["javacopts"].append(rule["javacopts"])
        model["srcs"].extend(rule["srcs"])

        for dep_list in ("deps", "runtime_deps"):
            for dep in rule[dep_list]:

                if dep.startswith("@maven//"):
                    model["maven_deps"].add(dep)

                elif not dep.startswith("//"):
                    model["other_deps"].add(dep)

    # Now resolve the complete transitive dependency closure.
    for rule in rules:
        pkg = label_package(rule["name"])
        model = projects[pkg]

        deps = query_transitive_deps(workspace, rule["name"])

        for dep in deps:
            # Maven dependencies must also be included transitively.
            # This is important for JDT because the generated .classpath
            # must contain the complete compile classpath, not only the
            # direct Maven dependencies declared in BUILD.bazel.
            if dep.startswith("@maven//"):
                model["maven_deps"].add(dep)
                continue

            dep_pkg = target_to_pkg.get(dep)

            if dep_pkg is None:
                continue

            if dep_pkg != pkg:
                model["internal_deps"].add(dep_pkg)

    return projects

def query_transitive_deps(workspace, label):
    """
    Return all Bazel targets transitively reachable from label.
    """
    output = run(
        [
            "bazel",
            "query",
            f"deps({label})",
            "--output=label",
            "--noimplicit_deps",
        ],
        cwd=workspace,
    )

    return {
        line.strip()
        for line in output.splitlines()
        if line.strip()
    }

def build_target_to_java_package(rules):
    """
    Map every Java Bazel target to the Eclipse project/package
    containing it.
    """
    result = {}

    for rule in rules:
        result[rule["name"]] = label_package(rule["name"])

    return result


def source_dirs_from_srcs(workspace, pkg_path, srcs):
    """
    Convert Bazel src labels/files into Eclipse source directories.

    Example:
        //foo/src/main/java/jadex/Foo.java
        //foo/src/generated/javacc/jadex/ParserImpl.java

    becomes:
        src/main/java
        src/generated/javacc
    """
    dirs = set()

    pkg_prefix = f"//{pkg_path}:" if pkg_path else "//:"

    for src in srcs:
        # External labels are not workspace source files.
        if not src.startswith(pkg_prefix):
            continue

        rel = src[len(pkg_prefix):]

        # Only actual source files.
        if not rel.endswith((".java", ".properties", ".xml", ".txt")):
            continue

        # Find the source root.
        parts = rel.split("/")

        if len(parts) < 2:
            continue

        # Known convention:
        #   src/main/java/...
        #   src/main/resources/...
        #   src/test/java/...
        #   src/test/resources/...
        #
        # This also naturally handles:
        #   src/generated/javacc/...
        #   src/generated/jjtree/...

        if len(parts) >= 3 and parts[0] == "src":
            if parts[1] in ("main", "test"):
                # src/main/java
                # src/main/resources
                if len(parts) >= 4:
                    dirs.add("/".join(parts[:3]))
            elif parts[1] == "generated":
                # src/generated/javacc
                # src/generated/jjtree
                if len(parts) >= 4:
                    dirs.add("/".join(parts[:3]))

    return sorted(dirs)


def write_project_file(pkg_dir, project_name, internal_deps):
    projects_xml = "\n".join(
        f"\t\t<project>{project_name_for_package(dep)}</project>"
        for dep in sorted(internal_deps)
    )
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- {AUTO_GEN_NOTICE} -->
<projectDescription>
\t<name>{project_name}</name>
\t<comment></comment>
\t<projects>
{projects_xml}
\t</projects>
\t<buildSpec>
\t\t<buildCommand>
\t\t\t<name>org.eclipse.jdt.core.javabuilder</name>
\t\t\t<arguments>
\t\t\t</arguments>
\t\t</buildCommand>
\t</buildSpec>
\t<natures>
\t\t<nature>org.eclipse.jdt.core.javanature</nature>
\t</natures>
</projectDescription>
"""
    with open(os.path.join(pkg_dir, ".project"), "w") as f:
        f.write(content)


def write_classpath_file(
    pkg_dir,
    src_dirs,
    internal_deps,
    maven_deps,
    maven_jars,
    jdk,
):
    """
    Write Eclipse .classpath.

    All classpath entries are collected first and deduplicated by their
    effective Eclipse classpath identity before being written.
    """

    # Key -> XML entry
    # The key is deliberately independent of the Maven/Bazel label.
    entries = {}

    def add_entry(key, xml):
        entries[key] = xml

    # Source directories
    for src in src_dirs:
        add_entry(
            ("src", src),
            f'\t<classpathentry kind="src" path="{src}"/>',
        )

    # JRE
    jre_path = (
        f"org.eclipse.jdt.launching.JRE_CONTAINER/"
        f"org.eclipse.jdt.internal.debug.ui.launcher."
        f"StandardVMType/JavaSE-{jdk}"
    )

    add_entry(
        ("con", jre_path),
        f'\t<classpathentry kind="con" path="{jre_path}"/>',
    )

    # Internal Eclipse project dependencies
    for dep_pkg in internal_deps:
        project_name = project_name_for_package(dep_pkg)
        path = f"/{project_name}"

        add_entry(
            ("project", path),
            f'\t<classpathentry combineaccessrules="false" '
            f'kind="src" path="{path}"/>',
        )

    missing = []

    # Maven dependencies
    for label in sorted(maven_deps):
        info = maven_jars.get(label)

        if not info:
            missing.append(label)
            continue

        # Normalize the actual physical JAR path.
        jar_path = os.path.normcase(
            os.path.normpath(info["jar"])
        )

        src_path = info.get("srcjar")
        if src_path:
            src_path = os.path.normcase(
                os.path.normpath(src_path)
            )

        # IMPORTANT:
        # Deduplicate by the actual JAR path, NOT by the Maven label.
        #
        # Thus:
        #
        #   @maven//:foo
        #   @maven//:foo_duplicate
        #
        # are still only one Eclipse classpath entry if both resolve
        # to the same physical JAR.
        add_entry(
            ("lib", jar_path),
            (
                f'\t<classpathentry kind="lib" '
                f'path="{jar_path}"'
                f'{f" sourcepath=\"{src_path}\"" if src_path else ""}/>'
            ),
        )

    # Output directory
    add_entry(
        ("output", "bin"),
        '\t<classpathentry kind="output" path="bin"/>',
    )

    # Write deterministic output.
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<classpath>",
        f"\t<!-- {AUTO_GEN_NOTICE} -->",
    ]

    for key in sorted(entries, key=str):
        lines.append(entries[key])

    lines.append("</classpath>")

    content = "\n".join(lines) + "\n"

    with open(os.path.join(pkg_dir, ".classpath"), "w") as f:
        f.write(content)

    return missing

def write_jdt_prefs(pkg_dir, jdk):
    settings_dir = os.path.join(pkg_dir, ".settings")
    os.makedirs(settings_dir, exist_ok=True)
    content = f"""eclipse.preferences.version=1
# {AUTO_GEN_NOTICE}
org.eclipse.jdt.core.compiler.codegen.targetPlatform={jdk}
org.eclipse.jdt.core.compiler.compliance={jdk}
org.eclipse.jdt.core.compiler.source={jdk}
"""
    with open(os.path.join(settings_dir, "org.eclipse.jdt.core.prefs"), "w") as f:
        f.write(content)


def clean_generated_files(workspace):
    """Delete all Eclipse/JDT project metadata from the workspace.

    This workspace is fully managed by generate_eclipse_projects.py.
    Therefore all .project, .classpath and .settings directories are
    considered generated/stale metadata and are removed before regeneration.
    """
    removed_projects = 0
    removed_classpaths = 0
    removed_settings = 0

    for dirpath, dirnames, filenames in os.walk(workspace, topdown=True):
        # Never descend into Bazel/VCS/build trees.
        dirnames[:] = [
            d for d in dirnames
            if d not in (
                ".git",
                "bazel-out",
                "bazel-bin",
                "bazel-testlogs",
            )
            and not d.startswith("bazel-")
        ]

        if ".project" in filenames:
            path = os.path.join(dirpath, ".project")
            print(f"  Removing {os.path.relpath(path, workspace)}")
            try:
                os.remove(path)
                removed_projects += 1
            except OSError as e:
                print(f"  WARNING: could not remove {path}: {e}")

        if ".classpath" in filenames:
            path = os.path.join(dirpath, ".classpath")
            print(f"  Removing {os.path.relpath(path, workspace)}")
            try:
                os.remove(path)
                removed_classpaths += 1
            except OSError as e:
                print(f"  WARNING: could not remove {path}: {e}")

        if ".settings" in dirnames:
            path = os.path.join(dirpath, ".settings")
            print(f"  Removing {os.path.relpath(path, workspace)}")
            try:
                shutil.rmtree(path)
                removed_settings += 1
            except OSError as e:
                print(f"  WARNING: could not remove {path}: {e}")

            # Do not descend into the directory we just removed.
            dirnames.remove(".settings")

    print(
        f"  Removed {removed_projects} .project file(s), "
        f"{removed_classpaths} .classpath file(s), "
        f"{removed_settings} .settings director{'y' if removed_settings == 1 else 'ies'}."
    )

    return removed_projects, removed_classpaths, removed_settings


def find_project_dirs(workspace):
    """Depth-first scan of the *entire* tree for every folder containing a
    .project file -- regardless of whether this script generated it. This
    catches leftover project files from earlier plugin attempts that Bazel
    itself doesn't know about (bazel query only sees Bazel packages)."""
    found = []
    for dirpath, dirnames, filenames in os.walk(workspace):
        # skip bazel's own convenience symlinks / vcs dirs -- huge and irrelevant
        dirnames[:] = [
            d for d in dirnames
            if not d.startswith("bazel-") and d not in (".git", "bazel-out")
        ]
        if ".project" in filenames:
            found.append(dirpath)
    return found


def prune_nested_projects(workspace):
    """Keep only the deepest project in any ancestor/descendant chain --
    Eclipse doesn't support nested projects. Auto-removes our own
    AUTO-GENERATED ancestor files; warns (without touching) about foreign
    ones so nothing unrelated gets silently deleted."""
    proj_dirs = sorted(find_project_dirs(workspace), key=len)
    proj_set = set(proj_dirs)
    removed, foreign_conflicts = [], []

    for d in proj_dirs:
        prefix = d + os.sep
        is_ancestor = any(other != d and other.startswith(prefix) for other in proj_set)
        if not is_ancestor:
            continue
        project_file = os.path.join(d, ".project")
        try:
            with open(project_file) as f:
                content = f.read()
        except OSError:
            continue
        if AUTO_GEN_NOTICE in content:
            os.remove(project_file)
            for extra in (".classpath",):
                p = os.path.join(d, extra)
                if os.path.isfile(p):
                    os.remove(p)
            settings = os.path.join(d, ".settings")
            if os.path.isdir(settings):
                shutil.rmtree(settings)
            removed.append(d)
        else:
            foreign_conflicts.append(d)

    return removed, foreign_conflicts

def existing_src_dirs(workspace, pkg_path):
    """Return all conventional source/resource directories that exist."""
    found = []
    pkg_abs = os.path.join(workspace, pkg_path)

    for candidate in SRC_DIR_CANDIDATES:
        if os.path.isdir(os.path.join(pkg_abs, candidate)):
            found.append(candidate)

    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workspace", default=".", help="Path to the Bazel workspace root (containing MODULE.bazel)")
    parser.add_argument("--jdk", type=int, default=21, help="Fallback JDK version if javacopts don't specify one")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be generated, write nothing")
    args = parser.parse_args()

    workspace = os.path.abspath(args.workspace)
    if not os.path.isfile(os.path.join(workspace, "MODULE.bazel")):
        raise SystemExit(f"No MODULE.bazel found in {workspace} -- pass --workspace correctly")

    if shutil.which("bazel") is None:
        raise SystemExit("bazel not found on PATH")

    if not args.dry_run:
        print("Removing all previously auto-generated project files (full clean rebuild) ...")
        removed = clean_generated_files(workspace)
        print(f"  Removed {len(removed)} previously generated project(s).")

    if not args.dry_run:
        print("Removing all bin directories from workspace ...")
        removed_bins = clean_all_bin_dirs(workspace)
        print(f"  Removed {len(removed_bins)} bin director{'y' if len(removed_bins) == 1 else 'ies'}.")

    print("Querying Bazel for all java_library/java_test/java_binary targets ...")
    rules = query_all_java_rules(workspace)
    if not rules:
        raise SystemExit("No matching Java targets found -- nothing to generate")

    projects = build_project_models(rules, workspace)

    # Eclipse does not support nested projects by default: a project's
    # folder cannot contain another project's folder. If one Bazel
    # package is a filesystem ancestor of another (e.g. a top-level
    # "everything" aggregate java_library at the workspace root, with
    # every other module living in subdirectories underneath it), skip
    # generating a project for the ancestor -- otherwise JDT LS throws a
    # ResourceException on that .project and aborts importing everything.
    all_pkgs = set(projects.keys())
    skipped_ancestors = set()
    for pkg in list(projects.keys()):
        prefix = pkg + "/" if pkg else ""
        if any(other != pkg and other.startswith(prefix) for other in all_pkgs):
            skipped_ancestors.add(pkg)
            del projects[pkg]

    if skipped_ancestors:
        print(
            "Skipping project generation for package(s) that are filesystem "
            "ancestors of other generated projects (Eclipse doesn't support "
            f"nested projects): {sorted(n or '<root>' for n in skipped_ancestors)}"
        )

    # Drop references to the now-skipped ancestor project(s) so we don't
    # emit .project entries pointing at a project that was never created.
    if skipped_ancestors:
        for model in projects.values():
            model["internal_deps"] -= skipped_ancestors

    all_maven_labels = set()
    for model in projects.values():
        all_maven_labels |= model["maven_deps"]

    print(
        f"Resolving {len(all_maven_labels)} Maven dependency target(s) "
        "via a single batched cquery ..."
    )

    maven_jars = resolve_maven_jars(all_maven_labels, workspace)

    print(
        f"  Resolved {len(maven_jars)}/{len(all_maven_labels)} "
        "Maven dependency target(s)."
    )

    for label in sorted(all_maven_labels):
        info = maven_jars.get(label)

        if info:
            print(f"  {label}")
            print(f"    JAR: {info['jar']}")

            if info["srcjar"]:
                print(f"    SRC: {info['srcjar']}")
        else:
            print(f"  MISSING: {label}")

    generated = 0
    all_missing = defaultdict(list)

    for pkg_path, model in sorted(projects.items()):
        project_name = project_name_for_package(pkg_path)
        pkg_dir = os.path.join(workspace, pkg_path)
        src_dirs = existing_src_dirs(workspace, pkg_path)
        jdk = guess_jdk_version(model["javacopts"], args.jdk)

        if model["other_deps"]:
            print(f"  [{project_name}] skipping non-maven external dep(s): {sorted(model['other_deps'])}")

        if args.dry_run:
            print(f"  would generate: {project_name}  (srcs={src_dirs}, "
                  f"internal_deps={len(model['internal_deps'])}, maven_deps={len(model['maven_deps'])})")
            continue

        write_project_file(pkg_dir, project_name, model["internal_deps"])
        missing = write_classpath_file(
            pkg_dir, src_dirs, model["internal_deps"], model["maven_deps"], maven_jars, jdk
        )
        write_jdt_prefs(pkg_dir, jdk)
        if missing:
            all_missing[project_name] = missing
        generated += 1

    if args.dry_run:
        print(f"\nDry run: {len(projects)} project(s) would be generated.")
        return

    print(f"\nGenerated {generated} Eclipse project(s) under {workspace}")
    if all_missing:
        print("\nWARNING: could not resolve jar files for these maven deps (cquery returned nothing):")
        for proj, labels in all_missing.items():
            print(f"  {proj}: {labels}")
        print("Usually fixed by running 'bazel build @maven//...' once so everything is fetched, then re-run this script.")

    print(
        "\nNext steps:\n"
        "  Eclipse: File > Import > General > Existing Projects into Workspace, point at the repo root.\n"
        "  VS Code: open the repo root (or add project folders as workspace folders) -- \n"
        "           the Java extension's Eclipse-project importer will pick them up automatically.\n"
        "  Re-run this script any time BUILD files / deps.bazel / maven artifacts change."
    )

    """print("\nScanning the full tree for nested project conflicts (Eclipse doesn't allow nested projects) ...")
    removed, foreign_conflicts = prune_nested_projects(workspace)
    if removed:
        print(f"  Removed {len(removed)} of our own ancestor project(s) that were nesting other projects:")
        for d in removed:
            print(f"    {os.path.relpath(d, workspace) or '.'}")
    if foreign_conflicts:
        print(
            "  WARNING: found foreign (not auto-generated) .project file(s) that still nest other "
            "projects and were left untouched -- these will keep breaking the import until you remove "
            "or relocate them by hand:"
        )
        for d in foreign_conflicts:
            print(f"    {os.path.join(d, '.project')}")
    if not removed and not foreign_conflicts:
        print("  No nesting conflicts found.")
    """

if __name__ == "__main__":
    main()
