import argparse
import os
import shutil
import subprocess
import sys
import tempfile
import time
import xml.etree.ElementTree as ET
from collections import defaultdict

# Collects (label, seconds) for every timed phase / subprocess call so we
# can print a "where did the time go" summary at the end of the run.
_TIMINGS = []


class timed:
    """Context manager: prints start/end + duration for a named phase and
    records it into _TIMINGS for the final summary table."""

    def __init__(self, label):
        self.label = label

    def __enter__(self):
        self.start = time.perf_counter()
        print(f"  >> {self.label} ...", flush=True)
        return self

    def __exit__(self, *exc):
        elapsed = time.perf_counter() - self.start
        _TIMINGS.append((self.label, elapsed))
        print(f"  << {self.label} -- {elapsed:.2f}s", flush=True)
        return False


def _short_cmd(cmd, maxlen=90):
    s = " ".join(cmd)
    return s if len(s) <= maxlen else s[:maxlen] + " ...[truncated]"

# Bazel rule kinds we turn into Eclipse projects.
SUPPORTED_KINDS = {"java_library", "java_test", "java_binary"}

# Conventional source directories we look for on disk inside each
# package. Adjust here if your layout ever differs from
# src/main/java, src/main/resources, src/test/java, src/test/resources.
SRC_DIR_CANDIDATES = [
    "src/main/java",
    "src/main/resources",
    "src/generated/javacc",
    "src/generated/jjtree",
    "src/test/java",
    "src/test/resources",
    "src/testFixtures/java",
    "src/testFixtures/resources",
]
AUTO_GEN_NOTICE = (
    "AUTO GENERATED by generate_eclipse_projects.py, do not hand edit, "
    "just re-run the script after Bazel deps change."
)

GENERATED_DIRS = {
    ".git",
    ".jdt-output",
    ".eclipse-bin",
    "bin",
}

# Above this length we pass query expressions via --query_file instead
# of as a raw command-line argument, to stay well clear of OS ARG_MAX
# limits once hundreds of labels get concatenated into one set(...) expr.
QUERY_FILE_THRESHOLD = 6000

# Cache `bazel info` lookups so repeated callers do not spawn extra bazel
# processes for values that stay constant within one script run.
_BAZEL_INFO_CACHE = {}


def run(cmd, cwd):
    """Run a subprocess, raise with full stderr on failure. Every call is
    timed and logged so slow bazel invocations show up immediately."""
    start = time.perf_counter()
    proc = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True
    )
    elapsed = time.perf_counter() - start
    _TIMINGS.append((f"subprocess: {_short_cmd(cmd)}", elapsed))
    print(f"    [{elapsed:7.2f}s] {_short_cmd(cmd)}", flush=True)

    if proc.returncode != 0:
        sys.stderr.write(f"$ {' '.join(cmd)}\n")
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"Command failed: {' '.join(cmd)}")
    return proc.stdout


def clean_workspace(workspace):
    """
    Single pass over the tree that removes both stale Eclipse project
    metadata (.project/.classpath/.settings) and bin/ output
    directories.

    This used to be two separate os.walk passes (clean_generated_files
    and clean_all_bin_dirs). Merging them into one halves the time
    spent just scanning the filesystem before Bazel even runs.
    """
    removed_projects = 0
    removed_classpaths = 0
    removed_settings = 0
    removed_bins = 0

    print(f"  Scanning {workspace} for generated metadata and bin/ dirs ...", flush=True)

    for dirpath, dirnames, filenames in os.walk(workspace, topdown=True):
        # Never descend into Bazel/VCS trees.
        dirnames[:] = [
            d for d in dirnames
            if d not in (".git", "bazel-out", "bazel-bin", "bazel-testlogs")
            and not d.startswith("bazel-")
        ]

        if ".project" in filenames:
            path = os.path.join(dirpath, ".project")
            print(f"  Removing {os.path.relpath(path, workspace)}", flush=True)
            try:
                os.remove(path)
                removed_projects += 1
            except OSError as e:
                print(f"  WARNING: could not remove {path}: {e}")

        if ".classpath" in filenames:
            path = os.path.join(dirpath, ".classpath")
            print(f"  Removing {os.path.relpath(path, workspace)}", flush=True)
            try:
                os.remove(path)
                removed_classpaths += 1
            except OSError as e:
                print(f"  WARNING: could not remove {path}: {e}")

        if ".settings" in dirnames:
            path = os.path.join(dirpath, ".settings")
            print(f"  Removing {os.path.relpath(path, workspace)}", flush=True)
            try:
                shutil.rmtree(path)
                removed_settings += 1
            except OSError as e:
                print(f"  WARNING: could not remove {path}: {e}")
            # Do not descend into the directory we just removed.
            dirnames.remove(".settings")

        if "bin" in dirnames:
            bin_dir = os.path.join(dirpath, "bin")
            print(f"  Removing {os.path.relpath(bin_dir, workspace)}", flush=True)
            try:
                shutil.rmtree(bin_dir)
                removed_bins += 1
            except OSError as e:
                print(f"  WARNING: could not remove {bin_dir}: {e}")
            # Do not descend into the directory we just removed.
            dirnames.remove("bin")

    print(
        f"  Removed {removed_projects} .project file(s), "
        f"{removed_classpaths} .classpath file(s), "
        f"{removed_settings} .settings director{'y' if removed_settings == 1 else 'ies'}, "
        f"{removed_bins} bin director{'y' if removed_bins == 1 else 'ies'}."
    )

    return removed_projects, removed_classpaths, removed_settings, removed_bins


def bazel_info(key, workspace):
    cache_key = (os.path.abspath(workspace), key)

    cached = _BAZEL_INFO_CACHE.get(cache_key)
    if cached is not None:
        return cached

    value = run(["bazel", "info", key], cwd=workspace).strip()
    _BAZEL_INFO_CACHE[cache_key] = value
    return value


def query_all_java_rules(workspace):
    """Single bazel query for every relevant java_* target in the repo."""
    kinds = "|".join(SUPPORTED_KINDS)
    expr = f'kind("^({kinds}) rule$", //...)'

    xml_text = run(
        ["bazel", "query", expr, "--output=xml", "--noimplicit_deps"],
        cwd=workspace,
    )

    root = ET.fromstring(xml_text)
    rules = []

    for rule in root.findall("rule"):
        data = {
            "kind": rule.get("class"),
            "name": rule.get("name"),
        }

        for list_name in ("srcs", "resources", "deps", "runtime_deps"):
            elem = rule.find(f"list[@name='{list_name}']")
            data[list_name] = (
                [lbl.get("value") for lbl in elem.findall("label")]
                if elem is not None
                else []
            )

        jc = rule.find("list[@name='javacopts']")
        data["javacopts"] = (
            [s.get("value") for s in jc.findall("string")]
            if jc is not None
            else []
        )

        rules.append(data)

    return rules


def label_package(label):
    """'//util/common:common' -> 'util/common'; '//:root' -> ''."""
    pkg = label.split(":")[0]
    return pkg[2:] if pkg.startswith("//") else pkg


def project_name_for_package(pkg_path):
    return pkg_path.replace("/", ".") if pkg_path else "root"


def guess_jdk_version(javacopts_lists, default_jdk):
    best = None
    for opts in javacopts_lists:
        for i, tok in enumerate(opts):
            if tok in ("-target", "--release", "-source") and i + 1 < len(opts):
                nxt = opts[i + 1]
                if nxt.isdigit():
                    best = max(best or 0, int(nxt))
    return best or default_jdk


def _cquery_jars_raw(labels, workspace):
    """Run ONE cquery over `labels` (as a set() expression) and return
    (stdout, returncode, stderr) -- unlike the old version this does NOT
    decide success/failure itself, so callers can inspect partial
    results even when --keep_going produced exit code 3."""
    label_set_expr = "set(" + " ".join(sorted(labels)) + ")"
    starlark_expr = (
        "'%s\t%s' % (str(target.label), "
        "','.join([f.path for f in target.files.to_list()] + "
        "[f.path for f in "
        "providers(target).get('@@rules_java+//java/private:java_info.bzl%JavaInfo', "
        "struct(source_jars=[])).source_jars]))"
    )

    cmd = ["bazel", "cquery"]
    query_file = None

    if len(label_set_expr) > QUERY_FILE_THRESHOLD:
        with tempfile.NamedTemporaryFile("w", suffix=".query", delete=False) as f:
            f.write(label_set_expr)
            query_file = f.name
        cmd += [f"--query_file={query_file}"]
    else:
        cmd += [label_set_expr]

    # --keep_going: one target in the set having an analysis/config
    # error must not abort the WHOLE query. Without this, bazel returns
    # zero results for the entire batch the moment ANY single target in
    # it is problematic -- which is exactly the "unreliable batching"
    # behaviour that forced falling back to one-call-per-label before.
    cmd += ["--output=starlark", "--starlark:expr", starlark_expr, "--keep_going"]

    start = time.perf_counter()
    try:
        proc = subprocess.run(cmd, cwd=workspace, capture_output=True, text=True)
    finally:
        if query_file:
            os.unlink(query_file)
    elapsed = time.perf_counter() - start
    _TIMINGS.append((f"cquery ({len(labels)} label(s)): {_short_cmd(cmd)}", elapsed))
    print(
        f"    [{elapsed:7.2f}s] cquery for {len(labels)} label(s) "
        f"(exit {proc.returncode})",
        flush=True,
    )

    return proc.stdout, proc.returncode, proc.stderr


def _resolve_chunk(labels, workspace, execroot, depth=0):
    """
    Resolve a batch of maven labels via cquery, recursively bisecting
    whatever's still missing after each attempt.

    Rationale: if a batched cquery over N labels fails/partially fails
    because of ONE incompatible label somewhere in the set, splitting
    the *missing* labels in half and retrying isolates the actual bad
    apple within a handful of extra calls -- instead of giving up on
    batching altogether and paying one full bazel invocation (~1s+)
    for every single one of the (likely hundreds of) labels that would
    have resolved together just fine.
    """
    if not labels:
        return {}, set()

    stdout, returncode, stderr = _cquery_jars_raw(labels, workspace)
    jars, seen_labels = _parse_cquery_jar_output(
        stdout, execroot, labels, include_seen=True
    )

    if returncode not in (0, 3) and not seen_labels:
        first_err_line = next((l for l in stderr.splitlines() if l.strip()), "")
        print(f"    NOTE: cquery hard-failed for {len(labels)} label(s): {first_err_line}")

    # Only recurse for labels that were not returned at all.
    # If bazel returned a label but no usable JAR path was found, retrying
    # the same label in smaller chunks is usually pointless.
    missing = [l for l in labels if l not in seen_labels]

    if not missing or len(labels) == 1:
        return jars, seen_labels

    # Stop subdividing once chunks get small: each bisection level costs
    # its own bazel call, so past this point it's cheaper to just let
    # resolve_maven_jars's final individual-fallback pass mop them up.
    if depth >= 5 or len(labels) <= 3:
        return jars, seen_labels

    mid = len(missing) // 2
    left_jars, left_seen = _resolve_chunk(missing[:mid], workspace, execroot, depth + 1)
    right_jars, right_seen = _resolve_chunk(missing[mid:], workspace, execroot, depth + 1)
    jars.update(left_jars)
    jars.update(right_jars)
    seen_labels.update(left_seen)
    seen_labels.update(right_seen)
    return jars, seen_labels


def _target_name(label):
    """Target-name portion of a label (after the last ':'). Used to
    correlate cquery results back to the labels we asked for: under
    bzlmod, `str(target.label)` in --output=starlark returns the
    *canonical* repo-mapped form (e.g. '@@rules_jvm_external+...+
    maven//:foo') which does NOT string-match the '@maven//:foo' we
    requested -- the target-name suffix is the one part guaranteed to
    stay identical."""
    return label.rsplit(":", 1)[-1]


def _parse_cquery_jar_output(stdout, execroot, requested_labels=None, include_seen=False):
    """Parse the '<label>\\t<paths>' lines from _cquery_jars_raw into
    {label: {"jar": ..., "srcjar": ...}}.

    If `requested_labels` is given, results are keyed by the ORIGINAL
    requested label (matched via target name) instead of whatever form
    bazel echoed back. Without this, every `label in jars` lookup
    downstream silently fails under bzlmod's canonical repo names, and
    every batch looks like a total miss even though bazel resolved
    everything correctly -- which is exactly what was forcing the
    bisection all the way down on every single chunk.
    """
    name_to_label = {}
    if requested_labels:
        for l in requested_labels:
            name_to_label[_target_name(l)] = l

    jars = {}
    seen_labels = set()

    for line in stdout.splitlines():
        line = line.strip()

        if not line or "\t" not in line:
            continue

        resolved_label, paths = line.split("\t", 1)
        key = name_to_label.get(_target_name(resolved_label), resolved_label)
        seen_labels.add(key)

        primary_jar = None
        source_jar = None

        for rel_path in paths.split(","):
            rel_path = rel_path.strip()

            if not rel_path.endswith(".jar"):
                continue

            abs_path = os.path.normpath(os.path.join(execroot, rel_path))

            if not os.path.isfile(abs_path):
                continue

            lower_name = os.path.basename(abs_path).lower()
            is_source = (
                lower_name.endswith("-sources.jar")
                or lower_name.endswith("-source.jar")
            )

            if is_source and source_jar is None:
                source_jar = abs_path
                continue

            if primary_jar is None:
                primary_jar = abs_path

        if primary_jar is None:
            continue

        # Fallback for layouts where source jars are present next to
        # the binary jar but not listed in target.files.
        if source_jar is None:
            candidate = primary_jar[:-4] + "-sources.jar"
            if os.path.isfile(candidate):
                source_jar = candidate

        jars[key] = {"jar": primary_jar, "srcjar": source_jar}

    if include_seen:
        return jars, seen_labels

    return jars


MAVEN_CHUNK_SIZE = 120
FINAL_RETRY_CHUNK_SIZE = 24


def resolve_maven_jars(maven_labels, workspace, execroot):
    """
    Resolve @maven//:... labels to actual JAR files.

    Labels are resolved in chunks (MAVEN_CHUNK_SIZE each) via cquery,
    with automatic recursive bisection of whatever a chunk doesn't
    resolve (see _resolve_chunk). This means one bad/incompatible
    target no longer forces one-bazel-call-per-label for everything --
    only the actual problem labels end up being queried individually,
    while the bulk resolves together in a handful of batched calls.
    """
    if not maven_labels:
        return {}

    labels_sorted = sorted(maven_labels)
    jars = {}
    seen_labels = set()

    chunks = [
        labels_sorted[i:i + MAVEN_CHUNK_SIZE]
        for i in range(0, len(labels_sorted), MAVEN_CHUNK_SIZE)
    ]

    with timed(
        f"chunked+bisecting cquery for {len(labels_sorted)} maven label(s) "
        f"({len(chunks)} chunk(s) of up to {MAVEN_CHUNK_SIZE})"
    ):
        for i, chunk in enumerate(chunks, 1):
            print(f"  chunk {i}/{len(chunks)}: {len(chunk)} label(s)")
            chunk_jars, chunk_seen = _resolve_chunk(chunk, workspace, execroot)
            jars.update(chunk_jars)
            seen_labels.update(chunk_seen)

    missing = [l for l in labels_sorted if l not in seen_labels]

    if missing:
        retry_chunks = [
            missing[i:i + FINAL_RETRY_CHUNK_SIZE]
            for i in range(0, len(missing), FINAL_RETRY_CHUNK_SIZE)
        ]

        with timed(
            f"straggler retry batches ({len(missing)} label(s), "
            f"{len(retry_chunks)} chunk(s) of up to {FINAL_RETRY_CHUNK_SIZE})"
        ):
            for i, chunk in enumerate(retry_chunks, 1):
                print(f"  retry chunk {i}/{len(retry_chunks)}: {len(chunk)} label(s)")
                chunk_jars, chunk_seen = _resolve_chunk(chunk, workspace, execroot)
                jars.update(chunk_jars)
                seen_labels.update(chunk_seen)

    missing = [l for l in labels_sorted if l not in seen_labels]

    if missing:
        with timed(
            f"final individual retries ({len(missing)} label(s), one bazel call EACH)"
        ):
            for index, label in enumerate(missing, 1):
                print(f"  [{index}/{len(missing)}] {label}")
                single_stdout, _, _ = _cquery_jars_raw([label], workspace)
                single_jars, single_seen = _parse_cquery_jar_output(
                    single_stdout, execroot, [label], include_seen=True
                )
                jars.update(single_jars)
                seen_labels.update(single_seen)

    total_with_sources = sum(1 for l in labels_sorted if l in jars and jars[l].get("srcjar"))
    total_resolved = sum(1 for l in labels_sorted if l in jars)
    print(
        f"  Source jars available for {total_with_sources}/{total_resolved} "
        "resolved Maven dependency target(s)."
    )

    print(
        f"  Resolved {len(jars)}/{len(labels_sorted)} "
        "Maven dependency target(s)."
    )

    for label in labels_sorted:
        if label not in jars:
            print(f"  WARNING: could not resolve Maven JAR: {label}")

    return jars


def query_transitive_deps_all(workspace, labels):
    """
    Compute the combined transitive dependency graph for every given
    label in a SINGLE bazel query, instead of one `bazel query
    deps(label)` per target (which used to mean one full bazel process
    start -- analysis included -- per java_library/java_test/
    java_binary in the repo).

    bazel's --output=xml format includes, for every rule node reached
    by the query, its direct dependency edges as <rule-input>
    elements. So one `deps(set(all_targets))` query gives us every
    edge we need in one shot; per-target transitive closures are then
    computed locally in Python via a plain BFS/DFS over that graph,
    which is essentially free compared to a bazel invocation.
    """
    label_set_expr = "set(" + " ".join(sorted(labels)) + ")"
    expr = f"deps({label_set_expr})"

    cmd = ["bazel", "query"]
    query_file = None

    if len(expr) > QUERY_FILE_THRESHOLD:
        with tempfile.NamedTemporaryFile("w", suffix=".query", delete=False) as f:
            f.write(expr)
            query_file = f.name
        cmd += [f"--query_file={query_file}", "--output=xml", "--noimplicit_deps"]
    else:
        cmd += [expr, "--output=xml", "--noimplicit_deps"]

    try:
        xml_text = run(cmd, cwd=workspace)
    finally:
        if query_file:
            os.unlink(query_file)

    root = ET.fromstring(xml_text)
    graph = defaultdict(set)

    for rule in root.findall("rule"):
        name = rule.get("name")
        for ri in rule.findall("rule-input"):
            graph[name].add(ri.get("name"))

    return graph


def transitive_closure(graph, start):
    """Plain BFS over the pre-fetched dependency graph -- no subprocess calls."""
    seen = set()
    stack = [start]

    while stack:
        cur = stack.pop()
        for dep in graph.get(cur, ()):
            if dep not in seen:
                seen.add(dep)
                stack.append(dep)

    return seen


def build_project_models(rules, workspace):
    """Build Eclipse project models from Bazel rules."""

    projects = defaultdict(
        lambda: {
            "internal_deps": set(),
            "maven_deps": set(),
            "other_deps": set(),
            "javacopts": [],
            "srcs": [],
        }
    )

    target_to_pkg = build_target_to_java_package(rules)

    # First collect sources and direct Maven deps.
    for rule in rules:
        pkg = label_package(rule["name"])
        model = projects[pkg]

        model["javacopts"].append(rule["javacopts"])
        model["srcs"].extend(rule["srcs"])

        for dep_list in ("deps", "runtime_deps"):
            for dep in rule[dep_list]:

                if dep.startswith("@maven//"):
                    model["maven_deps"].add(dep)

                elif not dep.startswith("//"):
                    model["other_deps"].add(dep)

    # Now resolve the complete transitive dependency closure -- for
    # ALL rules at once, via a single bazel query.
    all_labels = [rule["name"] for rule in rules]

    with timed(f"bazel deps() query for {len(all_labels)} target(s)"):
        dep_graph = query_transitive_deps_all(workspace, all_labels)

    print(f"  Dependency graph has {len(dep_graph)} node(s) with outgoing edges.")

    with timed(f"local BFS closure for {len(rules)} rule(s)"):
        for rule in rules:
            pkg = label_package(rule["name"])
            model = projects[pkg]

            deps = transitive_closure(dep_graph, rule["name"])

            for dep in deps:
                # Maven dependencies must also be included transitively.
                # This is important for JDT because the generated .classpath
                # must contain the complete compile classpath, not only the
                # direct Maven dependencies declared in BUILD.bazel.
                if dep.startswith("@maven//"):
                    model["maven_deps"].add(dep)
                    continue

                dep_pkg = target_to_pkg.get(dep)

                if dep_pkg is None:
                    continue

                if dep_pkg != pkg:
                    model["internal_deps"].add(dep_pkg)

    return projects


def build_target_to_java_package(rules):
    """
    Map every Java Bazel target to the Eclipse project/package
    containing it.
    """
    result = {}

    for rule in rules:
        result[rule["name"]] = label_package(rule["name"])

    return result


def source_dirs_from_srcs(workspace, pkg_path, srcs):
    """
    Convert Bazel src labels/files into Eclipse source directories.

    Example:
        //foo/src/main/java/jadex/Foo.java
        //foo/src/generated/javacc/jadex/ParserImpl.java

    becomes:
        src/main/java
        src/generated/javacc
    """
    dirs = set()

    pkg_prefix = f"//{pkg_path}:" if pkg_path else "//:"

    for src in srcs:
        # External labels are not workspace source files.
        if not src.startswith(pkg_prefix):
            continue

        rel = src[len(pkg_prefix):]

        # Only actual source files.
        if not rel.endswith((".java", ".properties", ".xml", ".txt")):
            continue

        # Find the source root.
        parts = rel.split("/")

        if len(parts) < 2:
            continue

        # Known convention:
        #   src/main/java/...
        #   src/main/resources/...
        #   src/test/java/...
        #   src/test/resources/...
        #
        # This also naturally handles:
        #   src/generated/javacc/...
        #   src/generated/jjtree/...

        if len(parts) >= 3 and parts[0] == "src":
            if parts[1] in ("main", "test"):
                # src/main/java
                # src/main/resources
                if len(parts) >= 4:
                    dirs.add("/".join(parts[:3]))
            elif parts[1] == "generated":
                # src/generated/javacc
                # src/generated/jjtree
                if len(parts) >= 4:
                    dirs.add("/".join(parts[:3]))

    return sorted(dirs)


def write_project_file(pkg_dir, project_name, internal_deps):
    projects_xml = "\n".join(
        f"\t\t<project>{project_name_for_package(dep)}</project>"
        for dep in sorted(internal_deps)
    )
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- {AUTO_GEN_NOTICE} -->
<projectDescription>
\t<name>{project_name}</name>
\t<comment></comment>
\t<projects>
{projects_xml}
\t</projects>
\t<buildSpec>
\t\t<buildCommand>
\t\t\t<name>org.eclipse.jdt.core.javabuilder</name>
\t\t\t<arguments>
\t\t\t</arguments>
\t\t</buildCommand>
\t</buildSpec>
\t<natures>
\t\t<nature>org.eclipse.jdt.core.javanature</nature>
\t</natures>
</projectDescription>
"""
    with open(os.path.join(pkg_dir, ".project"), "w") as f:
        f.write(content)


def write_non_java_project_file(pkg_dir, project_name):
    """Write a plain Eclipse project (no Java builder/nature)."""
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- {AUTO_GEN_NOTICE} -->
<projectDescription>
\t<name>{project_name}</name>
\t<comment>Workspace root helper project (non-Java).</comment>
\t<projects>
\t</projects>
\t<buildSpec>
\t</buildSpec>
\t<natures>
\t</natures>
</projectDescription>
"""
    with open(os.path.join(pkg_dir, ".project"), "w") as f:
        f.write(content)


def write_classpath_file(
    pkg_dir,
    src_dirs,
    internal_deps,
    maven_deps,
    maven_jars,
    jdk,
):
    """
    Write Eclipse .classpath.

    All classpath entries are collected first and deduplicated by their
    effective Eclipse classpath identity before being written.
    """

    # Key -> XML entry
    # The key is deliberately independent of the Maven/Bazel label.
    entries = {}

    def add_entry(key, xml):
        entries[key] = xml

    # Source directories
    for src in src_dirs:
        add_entry(
            ("src", src),
            f'\t<classpathentry kind="src" path="{src}"/>',
        )

    # JRE
    jre_path = (
        f"org.eclipse.jdt.launching.JRE_CONTAINER/"
        f"org.eclipse.jdt.internal.debug.ui.launcher."
        f"StandardVMType/JavaSE-{jdk}"
    )

    add_entry(
        ("con", jre_path),
        f'\t<classpathentry kind="con" path="{jre_path}"/>',
    )

    # Internal Eclipse project dependencies
    for dep_pkg in internal_deps:
        project_name = project_name_for_package(dep_pkg)
        path = f"/{project_name}"

        add_entry(
            ("project", path),
            f'\t<classpathentry combineaccessrules="false" '
            f'kind="src" path="{path}"/>',
        )

    missing = []

    # Maven dependencies
    for label in sorted(maven_deps):
        info = maven_jars.get(label)

        if not info:
            missing.append(label)
            continue

        # Normalize the actual physical JAR path.
        jar_path = os.path.normcase(
            os.path.normpath(info["jar"])
        )

        src_path = info.get("srcjar")
        if src_path:
            src_path = os.path.normcase(
                os.path.normpath(src_path)
            )

        # IMPORTANT:
        # Deduplicate by the actual JAR path, NOT by the Maven label.
        #
        # Thus:
        #
        #   @maven//:foo
        #   @maven//:foo_duplicate
        #
        # are still only one Eclipse classpath entry if both resolve
        # to the same physical JAR.
        add_entry(
            ("lib", jar_path),
            (
                f'\t<classpathentry kind="lib" '
                f'path="{jar_path}"'
                f'{f" sourcepath=\"{src_path}\"" if src_path else ""}/>'
            ),
        )

    # Output directory
    add_entry(
        ("output", "bin"),
        '\t<classpathentry kind="output" path="bin"/>',
    )

    # Write deterministic output.
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<classpath>",
        f"\t<!-- {AUTO_GEN_NOTICE} -->",
    ]

    for key in sorted(entries, key=str):
        lines.append(entries[key])

    lines.append("</classpath>")

    content = "\n".join(lines) + "\n"

    with open(os.path.join(pkg_dir, ".classpath"), "w") as f:
        f.write(content)

    return missing


def write_jdt_prefs(pkg_dir, jdk):
    settings_dir = os.path.join(pkg_dir, ".settings")
    os.makedirs(settings_dir, exist_ok=True)
    content = f"""eclipse.preferences.version=1
# {AUTO_GEN_NOTICE}
org.eclipse.jdt.core.compiler.codegen.targetPlatform={jdk}
org.eclipse.jdt.core.compiler.compliance={jdk}
org.eclipse.jdt.core.compiler.source={jdk}
"""
    with open(os.path.join(settings_dir, "org.eclipse.jdt.core.prefs"), "w") as f:
        f.write(content)


def find_project_dirs(workspace):
    """Depth-first scan of the *entire* tree for every folder containing a
    .project file -- regardless of whether this script generated it. This
    catches leftover project files from earlier plugin attempts that Bazel
    itself doesn't know about (bazel query only sees Bazel packages)."""
    found = []
    for dirpath, dirnames, filenames in os.walk(workspace):
        # skip bazel's own convenience symlinks / vcs dirs -- huge and irrelevant
        dirnames[:] = [
            d for d in dirnames
            if not d.startswith("bazel-") and d not in (".git", "bazel-out")
        ]
        if ".project" in filenames:
            found.append(dirpath)
    return found


def prune_nested_projects(workspace):
    """Keep only the deepest project in any ancestor/descendant chain --
    Eclipse doesn't support nested projects. Auto-removes our own
    AUTO-GENERATED ancestor files; warns (without touching) about foreign
    ones so nothing unrelated gets silently deleted."""
    proj_dirs = sorted(find_project_dirs(workspace), key=len)
    proj_set = set(proj_dirs)
    removed, foreign_conflicts = [], []

    for d in proj_dirs:
        prefix = d + os.sep
        is_ancestor = any(other != d and other.startswith(prefix) for other in proj_set)
        if not is_ancestor:
            continue
        project_file = os.path.join(d, ".project")
        try:
            with open(project_file) as f:
                content = f.read()
        except OSError:
            continue
        if AUTO_GEN_NOTICE in content:
            os.remove(project_file)
            for extra in (".classpath",):
                p = os.path.join(d, extra)
                if os.path.isfile(p):
                    os.remove(p)
            settings = os.path.join(d, ".settings")
            if os.path.isdir(settings):
                shutil.rmtree(settings)
            removed.append(d)
        else:
            foreign_conflicts.append(d)

    return removed, foreign_conflicts


def existing_src_dirs(workspace, pkg_path):
    """Return all conventional source/resource directories that exist."""
    found = []
    pkg_abs = os.path.join(workspace, pkg_path)

    for candidate in SRC_DIR_CANDIDATES:
        if os.path.isdir(os.path.join(pkg_abs, candidate)):
            found.append(candidate)

    return found


def _print_timing_summary(run_start):
    """Print a 'where did the time go' table: the slowest individual
    phases/subprocess calls first, plus the grand total wall time."""
    total = time.perf_counter() - run_start

    print("\n" + "=" * 72)
    print("TIMING SUMMARY (slowest first)")
    print("=" * 72)

    if not _TIMINGS:
        print("  (no timed operations recorded)")
    else:
        for label, elapsed in sorted(_TIMINGS, key=lambda t: -t[1])[:25]:
            pct = (elapsed / total * 100) if total else 0
            print(f"  {elapsed:8.2f}s  ({pct:5.1f}%)  {label}")

        # Break subprocess calls out separately since a single "phase"
        # (e.g. resolve maven jars) can be made up of dozens of them --
        # this shows whether the time is one slow bazel call or many
        # small ones (i.e. still-too-many-invocations).
        subproc_time = sum(e for l, e in _TIMINGS if l.startswith(("subprocess:", "cquery")))
        subproc_count = sum(1 for l, e in _TIMINGS if l.startswith(("subprocess:", "cquery")))
        if subproc_count:
            print(
                f"\n  Total: {subproc_count} bazel subprocess call(s) "
                f"took {subproc_time:.2f}s combined "
                f"({subproc_time / total * 100 if total else 0:.1f}% of total)."
            )

    print(f"\n  TOTAL WALL TIME: {total:.2f}s")
    print("=" * 72)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workspace", default=".", help="Path to the Bazel workspace root (containing MODULE.bazel)")
    parser.add_argument("--jdk", type=int, default=21, help="Fallback JDK version if javacopts don't specify one")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be generated, write nothing")
    parser.add_argument(
        "--skip-non-java-root-project",
        action="store_true",
        help="Do not generate a non-Java Eclipse .project in the workspace root",
    )
    args = parser.parse_args()

    workspace = os.path.abspath(args.workspace)
    if not os.path.isfile(os.path.join(workspace, "MODULE.bazel")):
        raise SystemExit(f"No MODULE.bazel found in {workspace} -- pass --workspace correctly")

    if shutil.which("bazel") is None:
        raise SystemExit("bazel not found on PATH")

    run_start = time.perf_counter()

    with timed("bazel info: execution_root"):
        execroot = bazel_info("execution_root", workspace)

    if not args.dry_run:
        with timed("clean workspace (metadata + bin/ dirs)"):
            clean_workspace(workspace)

    with timed("bazel query: enumerate java_* targets"):
        rules = query_all_java_rules(workspace)
    print(f"  Found {len(rules)} target(s).")

    if not rules:
        raise SystemExit("No matching Java targets found -- nothing to generate")

    with timed("build project models (deps graph + Maven dep collection)"):
        projects = build_project_models(rules, workspace)

    # Eclipse does not support nested projects by default: a project's
    # folder cannot contain another project's folder. If one Bazel
    # package is a filesystem ancestor of another (e.g. a top-level
    # "everything" aggregate java_library at the workspace root, with
    # every other module living in subdirectories underneath it), skip
    # generating a project for the ancestor -- otherwise JDT LS throws a
    # ResourceException on that .project and aborts importing everything.
    all_pkgs = set(projects.keys())
    skipped_ancestors = set()
    for pkg in list(projects.keys()):
        prefix = pkg + "/" if pkg else ""
        if any(other != pkg and other.startswith(prefix) for other in all_pkgs):
            skipped_ancestors.add(pkg)
            del projects[pkg]

    if skipped_ancestors:
        print(
            "Skipping project generation for package(s) that are filesystem "
            "ancestors of other generated projects (Eclipse doesn't support "
            f"nested projects): {sorted(n or '<root>' for n in skipped_ancestors)}"
        )

    # Drop references to the now-skipped ancestor project(s) so we don't
    # emit .project entries pointing at a project that was never created.
    if skipped_ancestors:
        for model in projects.values():
            model["internal_deps"] -= skipped_ancestors

    root_project_name = os.path.basename(workspace.rstrip(os.sep)) or "workspace"
    should_generate_non_java_root = (
        not args.skip_non_java_root_project
        and "" not in projects
    )

    all_maven_labels = set()
    for model in projects.values():
        all_maven_labels |= model["maven_deps"]

    with timed(f"resolve {len(all_maven_labels)} maven jar(s)"):
        maven_jars = resolve_maven_jars(all_maven_labels, workspace, execroot)

    for label in sorted(all_maven_labels):
        info = maven_jars.get(label)

        if info:
            print(f"  {label}")
            print(f"    JAR: {info['jar']}")

            if info["srcjar"]:
                print(f"    SRC: {info['srcjar']}")
        else:
            print(f"  MISSING: {label}")

    generated = 0
    all_missing = defaultdict(list)

    total_projects_to_write = len(projects) + (1 if should_generate_non_java_root else 0)

    with timed(f"write {total_projects_to_write} project(s) to disk (.project/.classpath/.settings)"):
        if should_generate_non_java_root:
            if args.dry_run:
                print(f"  would generate: {root_project_name}  (non-Java root project)")
            else:
                write_non_java_project_file(workspace, root_project_name)
                generated += 1

        for pkg_path, model in sorted(projects.items()):
            project_name = project_name_for_package(pkg_path)
            pkg_dir = os.path.join(workspace, pkg_path)
            src_dirs = existing_src_dirs(workspace, pkg_path)
            jdk = guess_jdk_version(model["javacopts"], args.jdk)

            if model["other_deps"]:
                print(f"  [{project_name}] skipping non-maven external dep(s): {sorted(model['other_deps'])}")

            if args.dry_run:
                print(f"  would generate: {project_name}  (srcs={src_dirs}, "
                      f"internal_deps={len(model['internal_deps'])}, maven_deps={len(model['maven_deps'])})")
                continue

            write_project_file(pkg_dir, project_name, model["internal_deps"])
            missing = write_classpath_file(
                pkg_dir, src_dirs, model["internal_deps"], model["maven_deps"], maven_jars, jdk
            )
            write_jdt_prefs(pkg_dir, jdk)
            if missing:
                all_missing[project_name] = missing
            generated += 1

    if args.dry_run:
        print(f"\nDry run: {total_projects_to_write} project(s) would be generated.")
        _print_timing_summary(run_start)
        return

    print(f"\nGenerated {generated} Eclipse project(s) under {workspace}")
    if all_missing:
        print("\nWARNING: could not resolve jar files for these maven deps (cquery returned nothing):")
        for proj, labels in all_missing.items():
            print(f"  {proj}: {labels}")
        print("Usually fixed by running 'bazel build @maven//...' once so everything is fetched, then re-run this script.")

    print(
        "\nNext steps:\n"
        "  Eclipse: File > Import > General > Existing Projects into Workspace, point at the repo root.\n"
        "  VS Code: open the repo root (or add project folders as workspace folders) -- \n"
        "           the Java extension's Eclipse-project importer will pick them up automatically.\n"
        "  Re-run this script any time BUILD files / deps.bazel / maven artifacts change."
    )

    _print_timing_summary(run_start)

    """print("\nScanning the full tree for nested project conflicts (Eclipse doesn't allow nested projects) ...")
    removed, foreign_conflicts = prune_nested_projects(workspace)
    if removed:
        print(f"  Removed {len(removed)} of our own ancestor project(s) that were nesting other projects:")
        for d in removed:
            print(f"    {os.path.relpath(d, workspace) or '.'}")
    if foreign_conflicts:
        print(
            "  WARNING: found foreign (not auto-generated) .project file(s) that still nest other "
            "projects and were left untouched -- these will keep breaking the import until you remove "
            "or relocate them by hand:"
        )
        for d in foreign_conflicts:
            print(f"    {os.path.join(d, '.project')}")
    if not removed and not foreign_conflicts:
        print("  No nesting conflicts found.")
    """


if __name__ == "__main__":
    main()