java -cp \
./application/micro/build/libs/application-micro.jar;\
./application/bdi/build/libs/application-bdi.jar;\
./serialization/binary/build/libs/binary.jar;\
./util/bytecode/build/libs/bytecode.jar;\
./util/classreader/build/libs/classreader.jar;\
./util/collection/build/libs/collection.jar;\
./util/common/build/libs/common.jar;\
./util/concurrent/build/libs/concurrent.jar;\
./engine/core/build/libs/core.jar;\
./engine/execution/build/libs/execution.jar;\
./util/future/build/libs/future.jar;\
./util/idgenerator/build/libs/idgenerator.jar;\
./util/javaparser/build/libs/javaparser.jar;\
./serialization/json/build/libs/json.jar;\
./engine/micro/build/libs/micro.jar;\
./engine/model/build/libs/model.jar;\
./engine/bdi/build/libs/bdi.jar;\
./rules/eca/build/libs/eca.jar;\
./util/nativetools/build/libs/nativetools.jar;\
./engine/providedservice/build/libs/providedservice.jar;\
./engine/providedservicemicro/build/libs/providedservicemicro.jar;\
./engine/publishservice/build/libs/publishservice.jar;\
./engine/publishservicejetty/build/libs/publishservicejetty.jar;\
./engine/requiredservice/build/libs/requiredservice.jar;\
./engine/requiredservicemicro/build/libs/requiredservicemicro.jar;\
./engine/serialization/build/libs/serialization.jar;\
./serialization/traverser/build/libs/traverser.jar;\
./serialization/json/build/libs/external-dependencies/minimal-json-0.9.5.jar;\
./engine/bdi/build/libs/external-dependencies/asm-9.1.jar;\
./engine/bdi/build/libs/external-dependencies/asm-tree-9.1.jar;\
./engine/bdi/build/libs/external-dependencies/asm-util-9.1.jar;\
./util/nativetools/build/libs/external-dependencies/jna-5.8.0.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jakarta.annotation-api-2.0.0.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jakarta.servlet-api-6.0.0.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jakarta.transaction-api-2.0.0.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jakarta.ws.rs-api-3.1.0.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-annotations-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-http-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-io-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-jakarta-servlet-api-5.0.2.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-jndi-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-plus-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-security-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-server-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-servlet-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-util-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-webapp-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jetty-xml-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/slf4j-api-2.0.0-alpha1.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/websocket-core-common-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/websocket-core-server-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/jakarta.annotation-api-2.0.0.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/websocket-jetty-api-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/websocket-jetty-common-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/websocket-jetty-server-11.0.6.jar;\
./engine/publishservicejetty/build/libs/external-dependencies/websocket-servlet-11.0.6.jar;\
./engine/requiredservice/build/libs/external-dependencies/nano-cuckoo-3.0.2.jar;\
./engine/requiredservice/build/libs/external-dependencies/lz4-1.3.0.jar \
jadex.micro.helloworld.HelloWorldAgent
# jadex.bdi.puzzle.Main
# jadex.micro.mandelbrot_new.MainWeb
# jadex.micro.gobble.GobbleAgent 