load("@rules_java//java:defs.bzl", "java_library", "java_test")

load(":deps.bzl", "DEPS")

load("//:maven_artifact.bzl", "maven_publish_jars")

ALL_DEPS = [
    "//util/common",
    "//util/collection",
    "//util/future",
    "//engine/core",
    "//feature/execution",
] + DEPS


java_library(
    name = "injection",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    javacopts = ["--release", "21"],
    deps = ALL_DEPS,
)

maven_publish_jars(
    name = "injection_publish",
    target = ":injection",
    deps = ALL_DEPS,
)

java_library(
    name = "injection_testfixtures",
    srcs = glob(["src/testFixtures/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    javacopts = ["--release", "21"],
    deps = [
        ":injection",
        "//benchmark/core:benchmark-core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_platform_junit_platform_suite_api",
    ] + ALL_DEPS,
)

java_test(
    name = "injection_test",
    srcs = glob(["src/test/java/**/*.java"]),
    main_class = "org.junit.platform.console.ConsoleLauncher",
    use_testrunner = False,
    args = [
        "--select-package", "jadex.injection",
        "--fail-if-no-tests",
    ],
    deps = [
        ":injection",
        ":injection_testfixtures",
        "//util/common",
        "//util/future",
        "//feature/result",
        "//benchmark/core:benchmark-core",
        "//engine/core",
        "//feature/execution",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_platform_junit_platform_suite_api",
    ],
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_suite_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_console",
    ],
)
