load("@rules_java//java:defs.bzl", "java_library", "java_test")

#load(":deps.bzl", "DEPS")

load("//:maven_artifacts.bzl", "maven_publish_jars")

ALL_DEPS = [
    "//util/common",
    "//util/collection",
    "//serialization/traverser",
    "//engine/core",
    "//serialization/json",
    "//serialization/binary",
] #+ DEPS

java_library(
    name = "serialization",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"], allow_empty = True,),
    visibility = ["//visibility:public"],
    javacopts = ["--release", "21"],
    deps = ALL_DEPS,
)

maven_publish_jars(
    name = "serialization_publish",
    target = ":serialization",
    deps = ALL_DEPS,
)


