load("//feature/configurator:feature.bzl", "feature")

feature(name = "benchmark-execution")

load("@rules_java//java:defs.bzl", "java_library", "java_test")

#load(":deps.bzl", "DEPS")

load("//:maven_artifact.bzl", "maven_publish_jars")

ALL_DEPS = [
    "//util/common:common",
    "//engine/core",
    "//monitoring/logbase",
    "//monitoring/opentelemetry",
    "//util/collection:collection",
    "//feature/execution",
    "//benchmark/core:benchmark-core",
    "//util/future",
] #+ DEPS

java_test(
    name = "execution_test",
    srcs = glob(["src/test/java/**/*.java"]),
    main_class = "org.junit.platform.console.ConsoleLauncher",
    use_testrunner = False,
    args = [
        "--fail-if-no-tests",
        "--select-package", "jadex.benchmark",
        "--include-classname", ".*",
    ],
    deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_platform_junit_platform_suite_api",
    ] + ALL_DEPS,
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_suite_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_console",
    ],
)

java_library(
    name = "benchmark-execution",
    srcs = [], #glob(["src/test/java/**/*.java"]),
    #resources = glob(["src/main/resources/**"], allow_empty = True,),
    visibility = ["//visibility:public"],
    javacopts = ["--release", "21"],
    #deps = ALL_DEPS,
)

maven_publish_jars(
    name = "benchmark-execution_publish",
    target = ":benchmark-execution",
    deps = ALL_DEPS,
)

