load("@rules_java//java:defs.bzl", "java_library")

load(":deps.bzl", "DEPS")

load("//:maven_artifact.bzl", "maven_publish_jars")

ALL_DEPS = [
    "//util/common",
    "//engine/core",
    "//feature/execution",
    "//util/future",
    "//monitoring/logbase"
] + DEPS

java_library(
    name = "fluentd",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    javacopts = ["--release", "21"],
    deps = ALL_DEPS
)

maven_publish_jars(
    name = "fluentd_publish",
    target = ":fluentd",
    deps = ALL_DEPS,
)
