load("@rules_java//java:defs.bzl", "java_library")

load("//:maven_artifacts.bzl", "maven_publish_jars")

ALL_DEPS = [
    "//util/common",
    "//util/collection",
    "//serialization/traverser",
    "//util/future",
    "//util/idgenerator:idgenerator",
] #+ DEPS

java_library(
    name = "core",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    javacopts = ["-source", "21", "-target", "21"],
    deps = ALL_DEPS,
)

maven_publish_jars(
    name = "core_publish",
    target = ":core",
    deps = ALL_DEPS,
)